version: '3.8'

services:
  api:
    build: .
    container_name: lks_api_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./klub_lks.db
      - SECRET_KEY=123
    restart: always